# Generated by Django 4.2.6 on 2023-10-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_label", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=256)),
                ("picture_file", models.CharField(max_length=64, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reduction", models.DecimalField(decimal_places=0, max_digits=3)),
                ("begin_promo", models.DateField(null=True)),
                ("end_promo", models.DateField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mercadona.category",
                    ),
                ),
            ],
        ),
    ]
