# Generated by Django 4.2.6 on 2023-10-27 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mercadona", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-picture_file"]},
        ),
    ]
