# Generated by Django 4.2.6 on 2023-10-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mercadona", "0003_alter_verifadmin_verification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="label",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
