# Generated by Django 4.2.6 on 2023-10-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mercadona", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifadmin",
            name="verification",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
